version: "3.4"

services:
  web:
    image: ambientum/php:7.4-nginx
    container_name: idez-web
    volumes:
      - .:/var/www/app:delegated
    ports:
      - 8000:8080
    environment:
      - PHP_MEMORY_LIMIT=-1
      - COMPOSER_MEMORY_LIMIT=-1
  db:
    image: mysql:5.7
    container_name: idez-data
    restart: unless-stopped
    tty: true
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: Jesusofsuburbia1@
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
volumes:
  idez-data:
    driver: local
